spring.application.name=Communication-professional-database
spring.datasource.url=jdbc:postgresql://portfolio_vzl9_user:dXpEzD6kl8mDDj39rExFMMvAMBO7X5P8@dpg-d8dfgvsm0tmc73dt19rg-a.oregon-postgres.render.com/portfolio_vzl9
spring.datasource.username=portfolio_vzl9_user
spring.datasource.password=dXpEzD6kl8mDDj39rExFMMvAMBO7X5P8
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=UTC

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging Levels
logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG

# spring.security.enabled=false
spring.security.user.name=user
spring.security.user.password=swastik2002

#CORS Links
frontend.url=https://shreyamukherjeeportfolio.vercel.app/

# Email configuration for Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shreyaportfolio123@gmail.com
spring.mail.password=obne hnfa tywt lgei 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000


